export * from './Header/Header';
export * from './MovieInfo/MovieInfo';
export * from './MoviesList/MoviesList';
export * from './GenreBadge/GenreBadge';
export * from './StarsRating/StarsRating';
export * from './MoviesListCard/MoviesListCard';
export * from './Pagination/Pagination';
export * from './SearchMovie/Search';
export * from './PosterPreview/PosterPreview';